"""
===============================================================================
FILE: run_viz.py
===============================================================================
Main script to generate the MyoSuite Kinematic Analysis Dashboard.
Runs all analyses (PCA, Metrics, Trajectories) and consolidates them into
a single HTML report.
"""

import os
import pandas as pd
import numpy as np
from tqdm import tqdm
import plotly.io as pio

# Import custom modules
from viz_utils import *
import viz_plots

# HTML Template
HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MyoSuite Kinematic Dashboard</title>
    <!-- Plotly JS -->
    
    <style>
        body { font-family: 'Segoe UI', sans-serif; margin: 0; padding: 0; background: #f8f9fa; color: #333; }
        .container { max-width: 1200px; margin: 0 auto; padding: 20px; }
        h1 { text-align: center; color: #2c3e50; margin-top: 20px; }
        .timestamp { text-align: center; color: #7f8c8d; font-size: 0.9em; margin-bottom: 40px; }
        
        .section { background: white; padding: 30px; margin-bottom: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.05); }
        h2 { color: #2980b9; border-bottom: 2px solid #3498db; padding-bottom: 10px; margin-top: 0; }
        p.desc { color: #666; font-style: italic; line-height: 1.6; margin-bottom: 25px; }
        
        .plot-container { text-align: center; }
        img { max-width: 100%; height: auto; border: 1px solid #eee; border-radius: 4px; }
        .gallery { display: flex; flex-wrap: wrap; justify-content: center; gap: 20px; }
        .gallery img { max-width: 48%; }
        
        footer { text-align: center; padding: 20px; color: #aaa; font-size: 0.8em; margin-top: 50px; }
    </style>
</head>
<body>

<div class="container">
    <h1>MyoSuite Kinematic Analysis</h1>
    <div class="timestamp">Generated by run_viz.py</div>

    <!-- SECTIONS -->
    {sections}

    <footer>Generated automatically by MyoSuite Utils</footer>
</div>

</body>
</html>
"""

def add_section(title, description, content_html):
    return f"""
    <div class="section">
        <h2>{title}</h2>
        <p class="desc">{description}</p>
        <div class="plot-container">
            {content_html}
        </div>
    </div>
    """

def main():
    print("🚀 Starting Dashboard Generation...")
    
    # --- 1. LOAD DATA ---
    print("📂 Loading Data...")
    
    # Load Scores
    if not os.path.exists(SCORES_FILE):
        print("❌ Scores file not found. Run analysis first.")
        return
    df_scores = pd.read_csv(SCORES_FILE)
    
    # Load Stroke MOTs (Flat & DF)
    mot_flat = []
    mot_dfs = {} # Cache for metrics
    mot_scores = []
    mot_files = []
    
    for idx, row in tqdm(df_scores.iterrows(), total=len(df_scores), desc="Loading MOTs"):
        path = os.path.join(DATA_DIR, row['filename'])
        if os.path.exists(path):
            # Flat for Manifolds
            flat = read_mot_file(path, resample=True)
            if flat is not None:
                mot_flat.append(flat)
                mot_scores.append(row['fma_score'])
                mot_files.append(row['filename'])
            
            # DF for Metrics/FK
            df_mot = read_mot_file(path, resample=False)
            if df_mot is not None:
                mot_dfs[row['filename']] = df_mot

    # Load TRCs (Markers)
    trc_flat = []
    trc_scores = []
    trc_files = []
    
    for idx, row in tqdm(df_scores.iterrows(), total=len(df_scores), desc="Loading TRCs"):
        trc_name = os.path.splitext(row['filename'])[0] + ".trc"
        path = os.path.join(DATA_DIR, trc_name)
        if os.path.exists(path):
            flat = read_trc_file(path)
            if flat is not None:
                trc_flat.append(flat)
                trc_scores.append(row['fma_score'])
                trc_files.append(trc_name)

    # Load CSVs (Source)
    # Note: Using glob on folders + matching with scores is tricky if filenames differ.
    # We will just load what we find in the CSV folders for the Comparison plot.
    csv_flat = []
    csv_labels = []
    csv_files = []
    
    s_files = glob.glob(os.path.join(STROKE_DIR, "*.csv"))[:30]
    h_files = glob.glob(os.path.join(HEALTHY_DIR, "*.csv"))[:30]
    
    for f in s_files:
        d = read_csv_file(f)
        if d is not None: 
            csv_flat.append(d)
            csv_labels.append("Stroke")
            csv_files.append(os.path.basename(f))
    for f in h_files:
        d = read_csv_file(f)
        if d is not None: 
            csv_flat.append(d)
            csv_labels.append("Healthy")
            csv_files.append(os.path.basename(f))


    # --- 2. GENERATE PLOTS & HTML ---
    sections_html = ""

    # SECTION 1: Raw Data Analysis (CSV Manifolds) - Using MOT data projected back or actual CSVs if matched?
    # Let's use the CSV data we loaded (Comparison).
    print("📊 Generating: CSV Comparison...")
    fig_csv = viz_plots.plot_manifolds(np.array(csv_flat), csv_labels, csv_files, "Source Data: Stroke vs Healthy")
    if fig_csv:
        sections_html += add_section(
            "1. Raw Data Comparison (Stroke vs Healthy)",
            "Direct comparison of Stroke patients (Red) vs Healthy controls (Blue) using Raw CSV data. Highlights global separation.",
            fig_csv.to_html(full_html=False, include_plotlyjs='cdn')
        )

    # SECTION 2: Marker Analysis (TRC)
    print("📊 Generating: Marker Manifolds...")
    if trc_flat:
        fig_trc = viz_plots.plot_manifolds(np.array(trc_flat), trc_scores, trc_files, "Optical Marker Data (TRC)")
        if fig_trc:
            sections_html += add_section(
                "2. Marker Data Analysis (TRC)",
                "Analysis of the Optical Marker data. Represents the motion before Inverse Kinematics.",
                fig_trc.to_html(full_html=False, include_plotlyjs='cdn')
            )

    # SECTION 3: Joint Analysis (MOT)
    print("📊 Generating: Joint Manifolds...")
    if mot_flat:
        fig_mot = viz_plots.plot_manifolds(np.array(mot_flat), mot_scores, mot_files, "Joint Angles (Inverse Kinematics)")
        if fig_mot:
            sections_html += add_section(
                "3. Inverse Kinematics Analysis (Joint Angles)",
                "Analysis of the final Joint Angles derived from the IK solver.",
                fig_mot.to_html(full_html=False, include_plotlyjs='cdn')
            )

    # SECTION 4: Stroke-Only Zoom (using subset of MOT)
    print("📊 Generating: Stroke-Only View...")
    stroke_indices = [i for i, s in enumerate(mot_scores) if s < 60]
    if stroke_indices:
        X_stroke = np.array(mot_flat)[stroke_indices]
        y_stroke = np.array(mot_scores)[stroke_indices]
        f_stroke = np.array(mot_files)[stroke_indices]
        
        fig_stroke = viz_plots.plot_manifolds(X_stroke, y_stroke, f_stroke, "Stroke Population Variance")
        if fig_stroke:
            sections_html += add_section(
                "4. Stroke-Only Analysis",
                "Zoomed-in view of the Stroke population variance, excluding healthy references.",
                fig_stroke.to_html(full_html=False, include_plotlyjs='cdn')
            )

    # SECTION 5: Model Quality
    print("📊 Generating: Model Quality...")
    if mot_flat:
        img_model = viz_plots.plot_model_quality(np.array(mot_flat), mot_scores)
        if img_model:
            sections_html += add_section(
                "5. Motion Generation Model Quality",
                "Validation of the generative model. The red line indicates the learned recovery path through the latent space.",
                f'<img src="{img_model}">'
            )

    # SECTION 6: Trajectories
    print("📊 Generating: Trajectories...")
    img_joints, img_3d = viz_plots.plot_trajectories(df_scores, mot_dfs)
    if img_joints and img_3d:
        content = f'<div class="gallery"><img src="{img_joints}"><img src="{img_3d}"></div>'
        sections_html += add_section(
            "6. Trajectory Analysis (Temporal & Spatial)",
            "Left: Average joint profiles (Mean +/- Std) grouped by impairment. Right: 3D paths of the wrist.",
            content
        )

    # SECTION 7: Metrics
    print("📊 Generating: Metrics...")
    img_metrics = viz_plots.plot_metrics(df_scores, mot_dfs)
    if img_metrics:
        sections_html += add_section(
            "7. Clinical Metrics Correlation",
            "Correlation between calculated kinematic metrics (ROM, Velocity, Efficiency) and the clinical FMA Score.",
            f'<img src="{img_metrics}">'
        )

    # SECTION 8: Similarity
    print("📊 Generating: Similarity...")
    if mot_flat:
        img_sim = viz_plots.plot_similarity(np.array(mot_flat), mot_files, mot_scores)
        if img_sim:
            sections_html += add_section(
                "8. Patient Similarity (Heatmap)",
                "Cluster map showing which patients move similarly based on Euclidean distance of joint trajectories.",
                f'<img src="{img_sim}">'
            )

    # --- 3. WRITE FILE ---
    final_html = HTML_TEMPLATE.replace("{sections}", sections_html)
    
    out_path = os.path.join(OUTPUT_DIR, "master_dashboard.html")
    with open(out_path, "w") as f:
        f.write(final_html)
        
    print(f"\n✅ Dashboard generated successfully at:\n   {out_path}")

if __name__ == "__main__":
    main()
